version: "3.8"
services:
  app:
    image: 'circadian-rhythm-sync:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=ema
      - POSTGRES_PASSWORD=H3lloW0rld!
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/circadian-sync-db
      - SPRING_DATASOURCE_USERNAME=ema
      - SPRING_DATASOURCE_PASSWORD=H3lloW0rld!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: "postgres:latest"
    container_name: db
    environment:
      - POSTGRES_DB=circadian-sync-db
      - POSTGRES_USER=ema
      - POSTGRES_PASSWORD=H3lloW0rld!
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local